package com.monster.demo.pojo.po.employee;

import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table employee_sensitive_info
 */
public class EmployeeSensitiveInfo {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_sensitive_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_sensitive_info.id_card_no_encrypt
     *
     * @mbg.generated
     */
    private String idCardNoEncrypt;

    /**
     * Database Column Remarks:
     *   电话号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_sensitive_info.phone_no_encrypt
     *
     * @mbg.generated
     */
    private String phoneNoEncrypt;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_sensitive_info.email_encrypt
     *
     * @mbg.generated
     */
    private String emailEncrypt;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_sensitive_info.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_sensitive_info.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_sensitive_info
     *
     * @mbg.generated
     */
    public EmployeeSensitiveInfo(Long id, String idCardNoEncrypt, String phoneNoEncrypt, String emailEncrypt, LocalDateTime gmtCreate, LocalDateTime gmtModified) {
        this.id = id;
        this.idCardNoEncrypt = idCardNoEncrypt;
        this.phoneNoEncrypt = phoneNoEncrypt;
        this.emailEncrypt = emailEncrypt;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_sensitive_info
     *
     * @mbg.generated
     */
    public EmployeeSensitiveInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_sensitive_info.id
     *
     * @return the value of employee_sensitive_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_sensitive_info.id
     *
     * @param id the value for employee_sensitive_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_sensitive_info.id_card_no_encrypt
     *
     * @return the value of employee_sensitive_info.id_card_no_encrypt
     *
     * @mbg.generated
     */
    public String getIdCardNoEncrypt() {
        return idCardNoEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_sensitive_info.id_card_no_encrypt
     *
     * @param idCardNoEncrypt the value for employee_sensitive_info.id_card_no_encrypt
     *
     * @mbg.generated
     */
    public void setIdCardNoEncrypt(String idCardNoEncrypt) {
        this.idCardNoEncrypt = idCardNoEncrypt == null ? null : idCardNoEncrypt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_sensitive_info.phone_no_encrypt
     *
     * @return the value of employee_sensitive_info.phone_no_encrypt
     *
     * @mbg.generated
     */
    public String getPhoneNoEncrypt() {
        return phoneNoEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_sensitive_info.phone_no_encrypt
     *
     * @param phoneNoEncrypt the value for employee_sensitive_info.phone_no_encrypt
     *
     * @mbg.generated
     */
    public void setPhoneNoEncrypt(String phoneNoEncrypt) {
        this.phoneNoEncrypt = phoneNoEncrypt == null ? null : phoneNoEncrypt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_sensitive_info.email_encrypt
     *
     * @return the value of employee_sensitive_info.email_encrypt
     *
     * @mbg.generated
     */
    public String getEmailEncrypt() {
        return emailEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_sensitive_info.email_encrypt
     *
     * @param emailEncrypt the value for employee_sensitive_info.email_encrypt
     *
     * @mbg.generated
     */
    public void setEmailEncrypt(String emailEncrypt) {
        this.emailEncrypt = emailEncrypt == null ? null : emailEncrypt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_sensitive_info.gmt_create
     *
     * @return the value of employee_sensitive_info.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_sensitive_info.gmt_create
     *
     * @param gmtCreate the value for employee_sensitive_info.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_sensitive_info.gmt_modified
     *
     * @return the value of employee_sensitive_info.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_sensitive_info.gmt_modified
     *
     * @param gmtModified the value for employee_sensitive_info.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}