package com.monster.demo.dao.employee;

import com.monster.demo.pojo.po.employee.EmployeeSensitiveInfo;

public interface EmployeeSensitiveInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_sensitive_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_sensitive_info
     *
     * @mbg.generated
     */
    int insert(EmployeeSensitiveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_sensitive_info
     *
     * @mbg.generated
     */
    int insertSelective(EmployeeSensitiveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_sensitive_info
     *
     * @mbg.generated
     */
    EmployeeSensitiveInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_sensitive_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmployeeSensitiveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_sensitive_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmployeeSensitiveInfo record);
}